PUT http://localhost:3001/home/64fb622b81e520a1636872de
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZmI2MjJiODFlNTIwYTE2MzY4NzJkZSIsImlhdCI6MTY5NDIwNzU4OH0.hyWZU1h1lWX_je-9dz8cO4QJh2Q8UDQ6Gq8fAGKI5dA

{
    "score": 2
}

###
PUT http://localhost:3001/home/64fb5930f89ad0b46eae9d08
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZmI1OTMwZjg5YWQwYjQ2ZWFlOWQwOCIsImlhdCI6MTY5NDIwODM5NX0.xw_fEz1SBvmRj5S9lw9vHPU6WL-EVy1LpaGLVVgA1z8

{
    "score": 10
}