POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "username": "Kanishk",
    "email": "Kanishk@gmail.com",
    "password": "password"
}
###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "devanshuguptaknp@gmail.com",
    "password": "password"
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "password"
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "Kanishk@gmail.com",
    "password": "password"
}


